language: ruby
rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-18mode
  - rbx-19mode
before_install: gem install bundler -v "~> 1.2.0"
bundler_args: --without doc releaseA

addons:
  code_climate:
    repo_token: 8f54d1653994973b85deca4c981fb8b03fbd25616e6f7c12f6728cbf3acf48bd
