language: ruby
cache: bundler
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - "2.1"
before_install: gem update bundler
env:
  global:
    - CC_TEST_REPORTER_ID=56a19efe95a8513862d3afb5bb3c02efc21d33a389b0f80a15e96e8590c84d40
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
bundler_args: --without doc release
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
